# PostgreSQL. Versions 8.2 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: 5

development:
  <<: *default
  database: new_eproduct_cart_development

test:
  <<: *default
  database: eproduct_cart_test

production:
  <<: *default
  database: eproduct_cart_production
